### ISSUE TITLE
Do You Plan on Adding YouTube/Gmail?

### ISSUE THREAD

**Issue by olivergb** [iojw/socialscan#1]
Do You Plan on Adding YouTube/Gmail?
It would be nice.

**Comment by iojw** [comment]
Implementing checking for Google accounts is possible but it's going to take some time to deconstruct the calls because it's more complex as compared to the other platforms. I'm looking into it.

As for Youtube, I can't currently do any testing at all for it because it requires me to have >100 subscribers to have a custom URL, so I probably won't be able to add that in unless somebody else does.

**Comment by olivergb** [comment]
Thanks for getting back to me on this. You’ve created a very useful application.
I’m thrilled to hear that you’re considering adding Google Account support.

Oliver Berman
Programmer
Cattaraugus-Allegany BOCES

**Comment by saikat-sarkar** [comment]
Hi,  please consider including Facebook also.

**Comment by iojw** [comment]
Closing this in favour of #16 - that will be the central issue for tracking the adding of new platforms.
